//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom6_DoAn_
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATVE
    {
        public string MAVE { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> GIAVE { get; set; }
        public string MAGHE { get; set; }
        public string MASUAT { get; set; }
        public string Email { get; set; }
    
        public virtual GHE GHE { get; set; }
        public virtual SUATCHIEU SUATCHIEU { get; set; }
    }
}
