//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom6_DoAn_
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatVe1
    {
        public string MaVe { get; set; }
        public string TrangThai { get; set; }
        public int GiaVe { get; set; }
        public string Email { get; set; }
        public string MaGhe { get; set; }
        public string MaSuat { get; set; }
    }
}
