//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom6_DoAn_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim1
    {
        public string MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string AnhBia { get; set; }
        public string TrailerUrl { get; set; }
        public string DaoDien { get; set; }
        public string DienVien { get; set; }
        public string TheLoai { get; set; }
        public int ThoiLuong { get; set; }
        public string NgonNgu { get; set; }
        public System.DateTime KhoiChieu { get; set; }
    }
}
