//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom6_DoAn_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN
    {
        public string MAQUYEN { get; set; }
        public string MATK { get; set; }
        public string MAVAITRO { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
