//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom6_DoAn_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RAPPHIMEntities : DbContext
    {
        public RAPPHIMEntities()
            : base("name=RAPPHIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<DATVE> DATVEs { get; set; }
        public virtual DbSet<DatVe1> DatVes1 { get; set; }
        public virtual DbSet<GHE> GHEs { get; set; }
        public virtual DbSet<Ghe1> Ghes1 { get; set; }
        public virtual DbSet<IdentityUserClaim> IdentityUserClaims { get; set; }
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<Phim1> Phims1 { get; set; }
        public virtual DbSet<PHONGCHIEU> PHONGCHIEUx { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<SUATCHIEU> SUATCHIEUx { get; set; }
        public virtual DbSet<SuatChieu1> SuatChieux1 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<Tbl_IdentityUserLogin> Tbl_IdentityUserLogin { get; set; }
        public virtual DbSet<Tbl_IndentityRoles> Tbl_IndentityRoles { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<VAITRO> VAITROes { get; set; }

        public System.Data.Entity.DbSet<Nhom6_DoAn_.Models.Phim> Phims { get; set; }
    }
}
