//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom6_DoAn_
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuatChieu1
    {
        public string MaSuat { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public System.TimeSpan KhungGio { get; set; }
        public string MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
    }
}
