// <auto-generated />
namespace Nhom6_DoAn_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update));
        
        string IMigrationMetadata.Id
        {
            get { return "202408040559234_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
